Created Jest snapshot test
asyncapi/nodejs-ws-template pull request #149
Opened 2021-12-29 15:47 UTC by Krishks369

Added jest snapshot tests for the template

2021-12-29 16:08 UTC, derberg requested changes
Looks good mate, added just few comments, some stuff are not needed

also remember to later commit updated package-lock, without removed deps

2021-12-29 16:08 UTC, derberg commented on test/integration.test.js
> +const crypto = require('crypto');
you can remove it as you do not use it

2021-12-29 16:08 UTC, derberg commented on test/integration.test.js
> +
please remove these white spaces, maybe run it through prettier or something

2021-12-29 16:08 UTC, derberg commented on test/integration.test.js
> +const URL = 'https://raw.githubusercontent.com/Krishks369/shrekapp-asyncapi-designed/main/asyncapi.yaml'
maybe we should use some official example, like https://raw.githubusercontent.com/asyncapi/spec/master/examples/social-media/frontend/asyncapi.yaml or https://github.com/asyncapi/generator/blob/master/test/docs/ws.yml ?

2021-12-29 16:08 UTC, derberg commented on package.json
> +    "node-yaml-config": "^1.0.0"
I don't think you are using these

2021-12-29 16:08 UTC, derberg commented on package.json
> +  "type": "module",
just curious, what does it change?

2021-12-29 16:08 UTC, derberg commented on package.json
> +    "start": "node src/api/index.js",
what does it start?

2021-12-30 05:29 UTC, Krishks369 commented
> Looks good mate, added just few comments, some stuff are not needed
> 
> also remember to later commit updated package-lock, without removed deps
 
I don't understand what you meant by deps?

2021-12-30 09:05 UTC, derberg commented
@Krishks369 oh sorry, by `deps` I meant `dependencies` 😅

2022-01-03 11:24 UTC, Krishks369 commented
@derberg Made the changes you asked. Check it now

2022-01-03 11:38 UTC, derberg commented on test/integration.test.js
> +			'README.md',
I just noticed that you are testing the wrong files. You test template sources, while you should test the output created from these templates.

snapshot integration tests purpose is to show you how the output changes basing on your changes to the template files.

so you should check `src/api/index.js` and others, but not under `template` but under the location where all gets generated, `outputDir`

2022-01-03 14:05 UTC, Krishks369 commented on test/integration.test.js
> +			'README.md',
Oh yea I will rectify it. Also do you want me to test docker and readme file also?

2022-01-03 14:11 UTC, derberg commented on test/integration.test.js
> +			'README.md',
no, enough is the service related files, js code

2022-01-03 14:41 UTC, derberg commented
I updated the PR title a bit to follow imperative mood  -> https://cbea.ms/git-commit/#imperative

2022-01-03 15:01 UTC, derberg commented
Interesting, I see this in test failure:
```
- router.ws('C:\echo', async (ws, req) => {
+ router.ws('/echo', async (ws, req) => {
```

I think it is related to https://github.com/asyncapi/nodejs-ws-template/issues/103
Can you try the workarounds mentioned there?

2022-01-11 09:50 UTC, derberg commented on filters/all.js
> +  return pathName;
oh this indent hurts my eyes 😄 ? sorry 😅
anyway, fault of the project that has no eslint not yours, 👍🏼 from my side

 if you want to contribute further to this project, plugging in eslint would be a good contribution, just take config and plugins that we use here https://github.com/asyncapi/generator

2022-01-11 09:51 UTC, derberg approved these changes
thanks a lot for this contribution! super useful!

2022-01-11 09:51 UTC, derberg commented
/rtm

2022-01-11 09:52 UTC, merged

2022-01-11 10:20 UTC, derberg commented
@all-contributors please add @Krishks369 for test