add eslint
asyncapi/nodejs-ws-template pull request #158
Opened 2022-01-15 12:40 UTC by Krishks369

Added eslint to template for better readability

2022-01-15 13:45 UTC, derberg requested changes
great job mate!
there is just one thing to improve

later if you have time, would love to get the same PR in https://github.com/asyncapi/nodejs-template 🙏🏼

2022-01-15 13:45 UTC, derberg commented on .eslintignore
> +template/src/lib/asyncapi.js
shouldn't entire `template` dir be ignored?
also make sure to remove empty spaces please

2022-01-15 14:25 UTC, Krishks369 commented on .eslintignore
> +template/src/lib/asyncapi.js
Done:+1:

2022-01-15 14:26 UTC, Krishks369 commented
> great job mate! there is just one thing to improve
> 
> later if you have time, would love to get the same PR in https://github.com/asyncapi/nodejs-template 🙏🏼

Sure, will do it

2022-01-15 14:48 UTC, derberg commented
oh, sorry mate
you were actually right
now I know why you ignored only specific files
you ignored the templates, but not all files are templated, thus can be checked by eslint.

sorry about it 😞  just please bring back previous state of `.eslintignore` and only remove empty lines 🙏🏼

2022-01-15 14:56 UTC, derberg approved these changes
LGTM 🚀

2022-01-17 11:06 UTC, derberg commented
/rtm

2022-01-17 11:06 UTC, merged